spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zeromoon277/springcloud-config.git
          search-paths: springcloud-config
          username: zeromoon277
          password: YYc153798
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 3344


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
