spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: payment_routh
#        uri: http://localhost:8001
        uri: lb://cloud-payment-service
        predicates:
        - Path=/payment/save/**

      - id: payment_routh2
#        uri: http://localhost:8001
        uri: lb://cloud-payment-service
        predicates:
          - Path=/payment/discovery/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway9527
    prefer-ip-address: true
server:
  port: 9527
